/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWeatherRouteImport } from './routes/_layout/weather'
import { Route as LayoutSmartMapThreeRouteImport } from './routes/_layout/smartMapThree'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSafeAlertAgentRouteImport } from './routes/_layout/safeAlertAgent'
import { Route as LayoutMysqlUsersRouteImport } from './routes/_layout/mysqlUsers'
import { Route as LayoutMysqlLocationsRouteImport } from './routes/_layout/mysqlLocations'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWeatherRoute = LayoutWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSmartMapThreeRoute = LayoutSmartMapThreeRouteImport.update({
  id: '/smartMapThree',
  path: '/smartMapThree',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSafeAlertAgentRoute = LayoutSafeAlertAgentRouteImport.update({
  id: '/safeAlertAgent',
  path: '/safeAlertAgent',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMysqlUsersRoute = LayoutMysqlUsersRouteImport.update({
  id: '/mysqlUsers',
  path: '/mysqlUsers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMysqlLocationsRoute = LayoutMysqlLocationsRouteImport.update({
  id: '/mysqlLocations',
  path: '/mysqlLocations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/mysqlLocations': typeof LayoutMysqlLocationsRoute
  '/mysqlUsers': typeof LayoutMysqlUsersRoute
  '/safeAlertAgent': typeof LayoutSafeAlertAgentRoute
  '/settings': typeof LayoutSettingsRoute
  '/smartMapThree': typeof LayoutSmartMapThreeRoute
  '/weather': typeof LayoutWeatherRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/mysqlLocations': typeof LayoutMysqlLocationsRoute
  '/mysqlUsers': typeof LayoutMysqlUsersRoute
  '/safeAlertAgent': typeof LayoutSafeAlertAgentRoute
  '/settings': typeof LayoutSettingsRoute
  '/smartMapThree': typeof LayoutSmartMapThreeRoute
  '/weather': typeof LayoutWeatherRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/mysqlLocations': typeof LayoutMysqlLocationsRoute
  '/_layout/mysqlUsers': typeof LayoutMysqlUsersRoute
  '/_layout/safeAlertAgent': typeof LayoutSafeAlertAgentRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/smartMapThree': typeof LayoutSmartMapThreeRoute
  '/_layout/weather': typeof LayoutWeatherRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/mysqlLocations'
    | '/mysqlUsers'
    | '/safeAlertAgent'
    | '/settings'
    | '/smartMapThree'
    | '/weather'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/mysqlLocations'
    | '/mysqlUsers'
    | '/safeAlertAgent'
    | '/settings'
    | '/smartMapThree'
    | '/weather'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/mysqlLocations'
    | '/_layout/mysqlUsers'
    | '/_layout/safeAlertAgent'
    | '/_layout/settings'
    | '/_layout/smartMapThree'
    | '/_layout/weather'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/weather': {
      id: '/_layout/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof LayoutWeatherRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/smartMapThree': {
      id: '/_layout/smartMapThree'
      path: '/smartMapThree'
      fullPath: '/smartMapThree'
      preLoaderRoute: typeof LayoutSmartMapThreeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/safeAlertAgent': {
      id: '/_layout/safeAlertAgent'
      path: '/safeAlertAgent'
      fullPath: '/safeAlertAgent'
      preLoaderRoute: typeof LayoutSafeAlertAgentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mysqlUsers': {
      id: '/_layout/mysqlUsers'
      path: '/mysqlUsers'
      fullPath: '/mysqlUsers'
      preLoaderRoute: typeof LayoutMysqlUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mysqlLocations': {
      id: '/_layout/mysqlLocations'
      path: '/mysqlLocations'
      fullPath: '/mysqlLocations'
      preLoaderRoute: typeof LayoutMysqlLocationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutMysqlLocationsRoute: typeof LayoutMysqlLocationsRoute
  LayoutMysqlUsersRoute: typeof LayoutMysqlUsersRoute
  LayoutSafeAlertAgentRoute: typeof LayoutSafeAlertAgentRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSmartMapThreeRoute: typeof LayoutSmartMapThreeRoute
  LayoutWeatherRoute: typeof LayoutWeatherRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutMysqlLocationsRoute: LayoutMysqlLocationsRoute,
  LayoutMysqlUsersRoute: LayoutMysqlUsersRoute,
  LayoutSafeAlertAgentRoute: LayoutSafeAlertAgentRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSmartMapThreeRoute: LayoutSmartMapThreeRoute,
  LayoutWeatherRoute: LayoutWeatherRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
